// Users
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_USERS_LOADING = "FETCH_USERS_LOADING";
export const FETCH_USERLIST_REPOS = "FETCH_USERLIST_REPOS";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_VIEW_MODE = "SET_VIEW_MODE";

// User
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
export const FETCH_USER_LOADING = "FETCH_USER_LOADING";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USERPAGE_REPOS = "FETCH_USERPAGE_REPOS";
export const FETCH_USERPAGE_ORGS = "FETCH_USERPAGE_ORGS";
