// Users
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_USERS_LOADING = "FETCH_USERS_LOADING";
export const SET_VIEW_MODE = "SET_VIEW_MODE";

// User
export const FETCH_USER_REPOS = "FETCH_USER_REPOS";
