// Users
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_USERS_LOADING = "FETCH_USERS_LOADING";

// User
export const FETCH_USER_REPOS = "FETCH_USER_REPOS";
